# Generated by Django 3.2.8 on 2021-11-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_img', models.CharField(max_length=500)),
                ('pro_name', models.CharField(max_length=255)),
                ('pro_quantity', models.IntegerField()),
                ('pro_rate', models.IntegerField()),
            ],
        ),
    ]
